import { test, expect } from "@playwright/test";

test.describe("Homepage", () => {
    test("should load the homepage", async ({ page }) => {
        await page.goto("/");

        // Check if the page loads
        await expect(page).toHaveTitle(/Create Next App/);

        // Check if layout components are present
        await expect(page.locator("header")).toBeVisible();
        await expect(page.locator("footer")).toBeVisible();
    });

    test("should have proper meta tags", async ({ page }) => {
        await page.goto("/");

        // Check meta description
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute(
            "content",
            /Generated by create next app/
        );
    });

    test("should be responsive", async ({ page }) => {
        await page.goto("/");

        // Test mobile viewport
        await page.setViewportSize({ width: 375, height: 667 });
        await expect(page.locator("header")).toBeVisible();

        // Test desktop viewport
        await page.setViewportSize({ width: 1920, height: 1080 });
        await expect(page.locator("header")).toBeVisible();
    });

    test("should have accessible structure", async ({ page }) => {
        await page.goto("/");

        // Check for proper heading structure
        const headings = page.locator("h1, h2, h3, h4, h5, h6");
        await expect(headings.first()).toBeVisible();

        // Check for proper landmark roles
        await expect(page.locator("header")).toHaveAttribute("role", "banner");
        await expect(page.locator("footer")).toHaveAttribute(
            "role",
            "contentinfo"
        );
    });
});
